name: Hackathon Submission
description: Add a hackathon submission
title: "[Project]: "
labels: ["submission", "needreview"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for participating in the hackathon and creating your submission!
  - type: input
    id: name
    attributes:
      label: Name
      description: Enter your full name
      placeholder: Aditya Oberai
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email Address
      description: Enter your email address
      placeholder: foo@bar.com
    validations:
      required: true
  - type: input
    id: project-link
    attributes:
      label: Project Repo
      description: Share a public repo link of your project
      placeholder: https://github.com/code-capture/CodeCapture-Xamarin
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Rules and Code of Conduct
      description: By submitting this issue, you agree to follow our Rules and Code of Conduct.
      options:
        - label: I agree to follow this hackathon's Rules and Code of Conduct
          required: true
